# Generated by Django 3.2 on 2023-12-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email адрес')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер телефона')),
                ('whatsapp_phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер Whatsapp')),
                ('is_employer', models.BooleanField(default=False, verbose_name='Работадатель')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_student', models.BooleanField(default=False, verbose_name='Студент')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('is_verified_email', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания кода подтверждения')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
