# Generated by Django 3.2 on 2024-02-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_employer', 'Работодатель'), ('is_student', 'Соискатель')], max_length=50, verbose_name='Роль'),
        ),
    ]
