# Generated by Django 3.2 on 2023-08-25 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.employercompany', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.university', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.employercompany', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='interview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='interview',
            name='vacancy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='employer_company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='core.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='bill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounts.profile', verbose_name='Оплатил'),
        ),
        migrations.AddField(
            model_name='bill',
            name='who_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='Оплату принял'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ProfileInArchive',
            fields=[
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInContactDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInEmbassy',
            fields=[
            ],
            options={
                'verbose_name': 'Посольство',
                'verbose_name_plural': 'Посольство',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInEssentialInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Справочная информация',
                'verbose_name_plural': 'Справочная информация',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInInterview',
            fields=[
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседование',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInRefused',
            fields=[
            ],
            options={
                'verbose_name': 'Отказавшиеся',
                'verbose_name_plural': 'Отказавшиеся',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'На регистрации',
                'verbose_name_plural': 'На регистрации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInSending',
            fields=[
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInTermin',
            fields=[
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileInVacancy',
            fields=[
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
                'ordering': ['termin', 'last_name', 'first_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfileNotConfirmed',
            fields=[
            ],
            options={
                'verbose_name': 'Общий список',
                'verbose_name_plural': 'Общий список',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AddField(
            model_name='profile',
            name='director_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.staff', verbose_name='Ответственный менеджер'),
        ),
    ]
