# Generated by Django 3.2 on 2023-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agreement1_download_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки Договора на тренинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agreement2_download_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки Договора на трудоустройство'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agreement3_download_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки Договора на тренинг 6000'),
        ),
    ]
