# Generated by Django 4.2 on 2024-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_employer', 'Работодатель'), ('is_employee', 'Сотрудник'), ('is_student', 'Соискатель')], max_length=50, verbose_name='Роль'),
        ),
    ]
