# Generated by Django 3.2 on 2024-01-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240102_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_employer', 'Работодатель'), ('is_employee', 'Соискатель')], default=1, max_length=50, verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
