# Generated by Django 3.2 on 2024-01-09 04:01

import applications.accounts.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240103_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=1, verbose_name='Значение рейтинга')),
                ('rating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата рейтинга')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Понедельник')),
                ('tuesday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Вторник')),
                ('wednesday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Среда')),
                ('thursday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Четверг')),
                ('friday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Пятница')),
                ('saturday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Суббота')),
                ('sunday', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], default='DAY', max_length=50, verbose_name='Воскресенье')),
                ('custom', models.CharField(blank=True, choices=[('DAY', 'День (08:00-20:00)'), ('EVENING', 'Ночь (17:00-01:00)'), ('NIGHT', 'Вечер (20:00-08:00)'), ('ANY', 'Свой график')], max_length=50, verbose_name='Свой график')),
                ('custom_start_time', models.TimeField(blank=True, help_text='Введите время в формате HH:MM', null=True, verbose_name='Начало работы (Свой график)')),
                ('custom_end_time', models.TimeField(blank=True, help_text='Введите время в формате HH:MM', null=True, verbose_name='Окончание работы (Свой график)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работ',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_company', models.CharField(blank=True, choices=[('Отель', 'Hotel'), ('Ресторан', 'Restaurant'), ('Кафе', 'Cafe'), ('Фабрика', 'Factory'), ('Салон', 'Salon'), ('Продажи', 'Sales'), ('Другое', 'Other')], max_length=50, verbose_name='Тип компании')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('position', models.CharField(blank=True, choices=[('Менеджер', 'Manager'), ('Официант', 'Waiter'), ('Повар', 'Cook'), ('Продавец', 'Seller'), ('Водитель', 'Driver'), ('Кассир', 'Cashier'), ('Строитель', 'Builder'), ('Мясник', 'Butcher'), ('Пекарь', 'Backer'), ('Другое', 'Other')], max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('midlle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=applications.accounts.utils.user_directory_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='Фото профиля')),
                ('gender', models.CharField(blank=True, choices=[('Мужской', 'Men'), ('Женский', 'Women')], max_length=10, verbose_name='Пол')),
                ('nationality', models.CharField(blank=True, choices=[('Кыргызстан', 'Kyrgyzstan'), ('Россия', 'Russia'), ('Узбекистан', 'Uzbekistan'), ('Казахстан', 'Kazakhstan'), ('Таджикистан', 'Taikistan'), ('Другое', 'Another')], max_length=50, verbose_name='Национальность')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('language', models.CharField(blank=True, choices=[('Русский', 'Russian'), ('Кыргызский', 'Kyrgyz'), ('Английский', 'English'), ('Немецкий', 'German'), ('Французский', 'French'), ('Турецкий', 'Turkish'), ('Китайский', 'Chinese'), ('Другое', 'Another')], max_length=50, verbose_name='Язык')),
                ('language_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Уровень языка')),
                ('whatsapp_phone_number', models.CharField(blank=True, max_length=50, verbose_name='Номер Whatsapp')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.rating', verbose_name='Рейтинг')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.review', verbose_name='Отзыв')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.workexperience', verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Профиль соискателя',
                'verbose_name_plural': 'Профили соискателей',
            },
        ),
    ]
