# Generated by Django 3.2 on 2024-01-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_city_profile_rating_review_workexperience_workschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='accounts.profile', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.profile', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.profile', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='accounts.profile', verbose_name='Соискатель'),
        ),
    ]
