# Generated by Django 3.2 on 2023-09-26 10:32

import applications.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230914_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=35000, editable=False, max_digits=10, verbose_name='Остаток')),
                ('is_fully_paid', models.BooleanField(default=False, verbose_name='Оплачено полностью')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('due_date', models.DateField(default=applications.accounts.models.get_due_date, null=True, verbose_name='Крайний срок оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
