# Generated by Django 3.2 on 2024-01-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240116_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='language_level',
            new_name='language_level_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='profile',
            name='language_1',
            field=models.CharField(blank=True, choices=[('Русский', 'Russian'), ('Кыргызский', 'Kyrgyz'), ('Английский', 'English'), ('Немецкий', 'German')], max_length=50, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_2',
            field=models.CharField(blank=True, choices=[('Русский', 'Russian'), ('Кыргызский', 'Kyrgyz'), ('Английский', 'English'), ('Немецкий', 'German')], max_length=50, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_3',
            field=models.CharField(blank=True, choices=[('Русский', 'Russian'), ('Кыргызский', 'Kyrgyz'), ('Английский', 'English'), ('Немецкий', 'German')], max_length=50, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_4',
            field=models.CharField(blank=True, choices=[('Русский', 'Russian'), ('Кыргызский', 'Kyrgyz'), ('Английский', 'English'), ('Немецкий', 'German')], max_length=50, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level_2',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Уровень языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level_3',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Уровень языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level_4',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Уровень языка'),
        ),
    ]
