# Generated by Django 3.2 on 2024-01-24 09:49

import applications.accounts.models
import applications.accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240118_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_level_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_level_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_level_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_level_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='midlle_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_country_de',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Страна рождения на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_country_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Страна рождения на латинице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_country_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Страна рождения на кириллице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_region_de',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Область рождения на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_region_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Область рождения на латинице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_region_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Область рождения на кириллице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Знание английского языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя на кириллице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_de',
            field=models.CharField(blank=True, choices=[('Männlich', 'Männlich'), ('Weiblich', 'Weiblich')], max_length=50, verbose_name='Пол на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_en',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Пол на латинице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_ru',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=50, verbose_name='Пол на кириллице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Знание немецкого языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия на кирилице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество на латинице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество на кирилице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality_de',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гражданство на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гражданство на латинице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гражданство на кирилице'),
        ),
        migrations.AddField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя на латинице'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия на латинице'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(blank=True, choices=[('Manager', 'Менеджер'), ('Waiter', 'Официант'), ('Cook', 'Повар'), ('Seller', 'Продавец'), ('Driver', 'Водитель'), ('Cashier', 'Кассир'), ('Builder', 'Строитель'), ('Butcher', 'Мясник'), ('Backer', 'Пекарь'), ('Other', 'Другое')], max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='type_company',
            field=models.CharField(blank=True, choices=[('Hotel', 'Отель'), ('Restaurant', 'Ресторан'), ('Cafe', 'Кафе'), ('Factory', 'Фабрика'), ('Salon', 'Салон'), ('Sales', 'Продажи'), ('Other', 'Другое')], max_length=50, verbose_name='Тип компании'),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Название университета на кириллице')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Название университета на латинице')),
                ('name_de', models.CharField(blank=True, max_length=255, verbose_name='Название университета на немецком')),
                ('degree_type_ru', models.CharField(blank=True, choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура')], max_length=255, verbose_name='Тип обучения на кириллице')),
                ('degree_type_en', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=255, verbose_name='Тип обучения на латинице')),
                ('degree_type_de', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=255, verbose_name='Тип обучения на немецком')),
                ('faculty_ru', models.CharField(blank=True, max_length=255, verbose_name='Факультет на кириллице')),
                ('faculty_en', models.CharField(blank=True, max_length=255, verbose_name='Факультет на латинице')),
                ('faculty_de', models.CharField(blank=True, max_length=255, verbose_name='Факультет на немецком')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Адрес на кириллице')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Адрес на латинице')),
                ('address_de', models.CharField(blank=True, max_length=255, verbose_name='Адрес на немецком')),
                ('phone_number_university_ru', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона университета')),
                ('email_university', models.EmailField(blank=True, max_length=254, verbose_name='Email университета')),
                ('website_university', models.URLField(blank=True, verbose_name='Сайт университета')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Год поступления в университет')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Год окончания университета')),
                ('total_years', models.IntegerField(blank=True, null=True, verbose_name='Общее количество лет')),
                ('kurs_year', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Other', 'Другое')], max_length=5, verbose_name='Курс')),
                ('start_holiday', models.DateField(blank=True, null=True, verbose_name='Начало каникул')),
                ('end_holiday', models.DateField(blank=True, null=True, verbose_name='Конец каникул')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='accounts.profile', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='Общая сумма')),
                ('total_amount_in_words', models.CharField(blank=True, max_length=255, verbose_name='Общая сумма прописью')),
                ('initial_fee', models.IntegerField(blank=True, null=True, verbose_name='Первоначальный взнос')),
                ('initial_fee_in_words', models.CharField(blank=True, max_length=255, verbose_name='Первоначальный взнос прописью')),
                ('average_fee', models.IntegerField(blank=True, null=True, verbose_name='Средний взнос')),
                ('average_fee_in_words', models.CharField(blank=True, max_length=255, verbose_name='Средний взнос прописью')),
                ('final_fee', models.IntegerField(blank=True, null=True, verbose_name='Окончательный взнос')),
                ('final_fee_in_words', models.CharField(blank=True, max_length=255, verbose_name='Окончательный взнос прописью')),
                ('debt', models.IntegerField(blank=True, null=True, verbose_name='Долг')),
                ('debt_in_words', models.CharField(blank=True, max_length=255, verbose_name='Долг прописью')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('payment_accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия оплаты')),
                ('payment_accepted', models.BooleanField(default=False, verbose_name='Оплата принята')),
                ('payment_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_accepted', to=settings.AUTH_USER_MODEL, validators=[applications.accounts.models.is_staff_or_superuser], verbose_name='Оплату принял')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.profile', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='PassportAndTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id_passport', models.CharField(blank=True, max_length=50, verbose_name='Номер ID паспорта')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Номер загран паспорта')),
                ('passport_date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_end_time', models.DateField(blank=True, null=True, verbose_name='Дата окончания загранпаспорта')),
                ('pnr_code', models.CharField(blank=True, max_length=50, verbose_name='PNR код')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=applications.accounts.utils.user_directory_path, verbose_name='PDF файл')),
                ('term_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время термина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_data', to='accounts.profile', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Паспортные данные и термин',
                'verbose_name_plural': 'Паспортные данные и термины',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('participant', models.CharField(blank=True, max_length=50, verbose_name='Участник')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Дата полета в Германию')),
                ('steuer_id', models.CharField(blank=True, max_length=50, verbose_name='Steuer ID - Налоговый номер')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('stage', models.CharField(blank=True, max_length=50, verbose_name='Стадия сделки')),
                ('program', models.CharField(blank=True, max_length=50, verbose_name='Программа')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата заключения договора')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='Комментарий')),
                ('hijab', models.CharField(blank=True, max_length=50, verbose_name='Носит Хиджаб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.profile', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
