# Generated by Django 3.2 on 2023-09-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supportrequest_supportresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInPayment',
        ),
        migrations.CreateModel(
            name='StudentDocumentsProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Документ Студента',
                'verbose_name_plural': 'Документы Студентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name', '-creation_date'], 'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
