# Generated by Django 3.2 on 2024-02-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240124_1549'),
    ]

    operations = [
        
    ]
