# Generated by Django 3.2 on 2024-02-06 05:19

import applications.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name_de',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_de',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия на немецком'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name_de',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество на немецком'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_accepted', to=settings.AUTH_USER_MODEL, validators=[applications.accounts.models.is_staff_or_superuser], verbose_name='Оплату принял'),
        ),
        migrations.AddIndex(
            model_name='passportandterm',
            index=models.Index(fields=['user'], name='accounts_pa_user_id_41adac_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'gender_en', 'german', 'russian'], name='accounts_pr_user_id_20decd_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['user'], name='accounts_un_user_id_51349f_idx'),
        ),
    ]
