# Generated by Django 3.2 on 2023-09-27 07:55

import applications.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230927_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж студента', 'verbose_name_plural': 'Платежи студентов'},
        ),
        migrations.AddField(
            model_name='payment',
            name='who_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='accounts.user', validators=[applications.accounts.models.is_staff_or_superuser], verbose_name='Оплату принял'),
            preserve_default=False,
        ),
    ]
