# Generated by Django 3.2 on 2023-09-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230927_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInArchive',
        ),
    ]
