# Generated by Django 3.2 on 2023-09-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_profileinarchive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInRefused',
        ),
        migrations.DeleteModel(
            name='ProfileInRegistration',
        ),
        migrations.DeleteModel(
            name='ProfileInSending',
        ),
        migrations.DeleteModel(
            name='ProfileInTermin',
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
            ],
            options={
                'verbose_name': 'Контакт студента',
                'verbose_name_plural': 'Контакты студентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
    ]
