# Generated by Django 3.2 on 2023-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chinese',
            field=models.CharField(blank=True, choices=[('В совершенстве', 'В совершенстве'), ('Хорошо', 'Хорошо'), ('Разговорный', 'Разговорный'), ('Обучаюсь', 'Обучаюсь'), ('Не знаю', 'Не знаю')], default='', max_length=150, verbose_name='Знание китайского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('В совершенстве', 'В совершенстве'), ('Хорошо', 'Хорошо'), ('Разговорный', 'Разговорный'), ('Обучаюсь', 'Обучаюсь'), ('Не знаю', 'Не знаю')], default='', max_length=150, verbose_name='Знание английского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('В совершенстве', 'В совершенстве'), ('Хорошо', 'Хорошо'), ('Разговорный', 'Разговорный'), ('Обучаюсь', 'Обучаюсь'), ('Не знаю', 'Не знаю')], default='', max_length=150, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('В совершенстве', 'В совершенстве'), ('Хорошо', 'Хорошо'), ('Разговорный', 'Разговорный'), ('Обучаюсь', 'Обучаюсь'), ('Не знаю', 'Не знаю')], default='', max_length=150, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='turkish',
            field=models.CharField(blank=True, choices=[('В совершенстве', 'В совершенстве'), ('Хорошо', 'Хорошо'), ('Разговорный', 'Разговорный'), ('Обучаюсь', 'Обучаюсь'), ('Не знаю', 'Не знаю')], default='', max_length=150, verbose_name='Знание турецкого языка'),
        ),
    ]
