# Generated by Django 3.2 on 2023-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20231002_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chinese',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание китайского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание английского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('a0', 'A0'), ('a1', 'A1'), ('a1+', 'A1+'), ('a2', 'A2'), ('a2+', 'A2+'), ('b1', 'B1'), ('b1+', 'B1+'), ('b2', 'B2'), ('b2+', 'B2+'), ('c1', 'C1')], default='', max_length=3, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='turkish',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание турецкого языка'),
        ),
    ]
