# Generated by Django 3.2 on 2023-10-09 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20231002_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('video', models.FileField(blank=True, null=True, upload_to='announcement_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_to_students', models.BooleanField(default=False, verbose_name='Отправить студентам')),
                ('send_to_employers', models.BooleanField(default=False, verbose_name='Отправить работодателям')),
                ('specific_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_announcements', to=settings.AUTH_USER_MODEL)),
                ('specific_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
