# Generated by Django 3.2 on 2023-10-20 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Емайл')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Примечание менеджера')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='Дата звонка менеджера')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('called', models.BooleanField(default=False, verbose_name='Позвонил')),
                ('consulted', models.BooleanField(default=False, verbose_name='Проконсультирован')),
                ('call_later', models.BooleanField(default=False, verbose_name='Набрать позже')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заявка на подключение',
                'verbose_name_plural': 'Заявки на подключение',
            },
        ),
    ]
