# Generated by Django 3.2 on 2023-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20231025_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_region',
            field=models.CharField(blank=True, choices=[('Tschui', 'Чуйская область'), ('Naryn', 'Нарынская область'), ('Talas', 'Таласская область'), ('Issik-Kul', 'Ыссык-Кульская область'), ('Zhalal-Abad', 'Жалал-Абадская область'), ('Osh', 'Ошская область'), ('Batken', 'Баткенская область')], default='', max_length=50, verbose_name='Область рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('бакалавр', 'Бакалавр'), ('магистр', 'Магистр'), ('колледж', 'Колледж')], default='', max_length=20, verbose_name='Академическая степень'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driving_experience',
            field=models.CharField(blank=True, choices=[('1', 'до 1 года'), ('2', '1 год'), ('3', '2 года'), ('4', '3 года'), ('5', '4 и более лет')], default='', max_length=1, verbose_name='Стаж вождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('a0', 'A0'), ('a1', 'A1'), ('a1+', 'A1+'), ('a2', 'A2'), ('a2+', 'A2+'), ('b1', 'B1'), ('b1+', 'B1+'), ('b2', 'B2'), ('b2+', 'B2+'), ('c1', 'C1')], default='', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position1',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (1 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position2',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (2 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position3',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (3 место работы)'),
        ),
    ]
