# Generated by Django 3.2 on 2023-12-25 07:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_0020_auto_20231113_1141_0020_auto_20231113_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания кода подтверждения'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='manager_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Примечание менеджера'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='arrival_place',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='living_condition',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AlterField(
            model_name='profilehistory',
            name='changes',
            field=ckeditor.fields.RichTextField(verbose_name='Текст изменения'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='supportresponse',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
    ]
