# Generated by Django 3.2 on 2024-02-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филлиала')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Текстовый адрес')),
                ('link_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на адрес')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание как добраться')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('icon', models.ImageField(blank=True, upload_to='company_icons/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('iin', models.CharField(max_length=50, verbose_name='ИИН/БИН')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Позиция работника',
                'verbose_name_plural': 'Позиция работников',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField(verbose_name='Обязанности')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('clothingform', models.CharField(max_length=255, verbose_name='Форма одежды')),
                ('employee_count', models.PositiveIntegerField(default=1, verbose_name='Количество работников')),
                ('employee_count_hired', models.PositiveIntegerField(default=0, verbose_name='Количество нанятых работников')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол')),
                ('time_start', models.TimeField(verbose_name='Время начала работы')),
                ('time_end', models.TimeField(verbose_name='Время окончания работы')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('description', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('views_vacancy', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('increase_choices', models.BooleanField(default=False, verbose_name='Повышение зарплаты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('language_german', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание немецкого языка')),
                ('language_english', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание английского языка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал')),
                ('employer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positionemployee', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='ReviewBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='', verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв филиала',
                'verbose_name_plural': 'Отзывы филиалов',
            },
        ),
        migrations.CreateModel(
            name='RatingEmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг компании',
                'verbose_name_plural': 'Рейтинги компаний',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение на вакансию',
                'verbose_name_plural': 'Приглашения на вакансии',
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('interviews_date', models.DateTimeField(verbose_name='Дата собеседования')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Не прошел')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Прошел')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_profile', to='accounts.profile', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer_company'], name='core_vacanc_employe_84c983_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['branch'], name='core_review_branch__bcbb89_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['user'], name='core_review_user_id_2e241b_idx'),
        ),
        migrations.AddIndex(
            model_name='positionemployee',
            index=models.Index(fields=['employer'], name='core_positi_employe_a49f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['employer'], name='core_invita_employe_6efbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['vacancy'], name='core_invita_vacancy_42e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['user'], name='core_invita_user_id_aaba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviews',
            index=models.Index(fields=['employer'], name='core_interv_employe_d265d5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviews',
            index=models.Index(fields=['vacancy'], name='core_interv_vacancy_39c9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='interviews',
            index=models.Index(fields=['user'], name='core_interv_user_id_9f9789_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['employer'], name='core_favori_employe_0b8eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='core_favori_user_id_cbe902_idx'),
        ),
        migrations.AddIndex(
            model_name='employercompany',
            index=models.Index(fields=['user'], name='core_employ_user_id_bc9c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='core_branch_city_id_97ceff_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company'], name='core_branch_company_9dd70f_idx'),
        ),
    ]
