# Generated by Django 4.2 on 2024-03-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(choices=[('Baden-Württemberg', 'Baden-Württemberg'), ('Bavaria', 'Bavaria'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Hamburg', 'Hamburg'), ('Hesse', 'Hesse'), ('Lower Saxony', 'Lower Saxony'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('North Rhine-Westphalia', 'North Rhine-Westphalia'), ('Rhineland-Palatinate', 'Rhineland-Palatinate'), ('Saarland', 'Saarland'), ('Saxony', 'Saxony'), ('Saxony-Anhalt', 'Saxony-Anhalt'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thuringia', 'Thuringia')], max_length=100)),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Название города')),
                ('name', models.CharField(max_length=255, verbose_name='Название филлиала')),
                ('address', models.CharField(max_length=255, verbose_name='Текстовый адрес')),
                ('link_address', models.CharField(max_length=255, verbose_name='Ссылка на адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание как добраться')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Контактные данные')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='Контактное лицо')),
                ('icon', models.ImageField(blank=True, upload_to='company_icons/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('iin', models.CharField(blank=True, max_length=50, verbose_name='ИИН/БИН')),
                ('payment_info', models.CharField(blank=True, max_length=255, verbose_name='Реквезиты компании')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(max_length=100, verbose_name='Тип жилья')),
                ('housing_cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость жилья')),
                ('additional_expenses', models.TextField(blank=True, verbose_name='Дополнительные расходы')),
                ('deposit', models.PositiveIntegerField(default=0, verbose_name='Залог')),
                ('cleaning', models.CharField(blank=True, max_length=255, verbose_name='Уборка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Жилье',
                'verbose_name_plural': 'Жилье',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('duty', models.TextField(verbose_name='Обязанности')),
                ('is_excperience', models.BooleanField(default=False, verbose_name='Опыт работы требуется')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('clothingform', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма одежды')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Транспорт')),
                ('insurance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страховка')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования работы')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия работы')),
                ('employee_count', models.PositiveIntegerField(default=1, verbose_name='Количество работников')),
                ('employee_count_hired', models.PositiveIntegerField(default=0, verbose_name='Количество нанятых работников')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол')),
                ('time_start', models.TimeField(verbose_name='Время начала работы')),
                ('time_end', models.TimeField(verbose_name='Время окончания работы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('start_holidays_date', models.DateField(verbose_name='Дата начала каникул')),
                ('end_holidays_date', models.DateField(verbose_name='Дата окончания каникул')),
                ('housing_status', models.BooleanField(default=False, verbose_name='Жилье предоставляется')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('language_german', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание немецкого языка')),
                ('language_english', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание английского языка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал')),
                ('employer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('housing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.housing', verbose_name='Жилье')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение на вакансию',
                'verbose_name_plural': 'Приглашения на вакансии',
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('interviews_date', models.DateTimeField(verbose_name='Дата собеседования')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Не прошел')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Прошел')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ManyToManyField(to='accounts.profile', verbose_name='Профиль студента')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
            },
        ),
        migrations.CreateModel(
            name='FilesHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='housing_files/', verbose_name='Файлы жилья')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.housing', verbose_name='Жилье')),
            ],
            options={
                'verbose_name': 'Файл жилья',
                'verbose_name_plural': 'Файлы жилья',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer_company'], name='core_vacanc_employe_84c983_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['employer'], name='core_invita_employe_6efbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['vacancy'], name='core_invita_vacancy_42e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['user'], name='core_invita_user_id_aaba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviews',
            index=models.Index(fields=['employer'], name='core_interv_employe_d265d5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviews',
            index=models.Index(fields=['vacancy'], name='core_interv_vacancy_39c9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='housing',
            index=models.Index(fields=['employer'], name='core_housin_employe_c9b38a_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['employer'], name='core_favori_employe_0b8eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='core_favori_user_id_cbe902_idx'),
        ),
        migrations.AddIndex(
            model_name='employercompany',
            index=models.Index(fields=['user'], name='core_employ_user_id_bc9c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company'], name='core_branch_company_9dd70f_idx'),
        ),
    ]
