# Generated by Django 3.2 on 2024-02-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.housing', verbose_name='Жилье'),
        ),
    ]
