# Generated by Django 3.2 on 2024-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingemployercompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ratingemployercompany',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewbranch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reviewbranch',
            name='user',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(default=1, max_length=255, verbose_name='Позиция'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PositionEmployee',
        ),
        migrations.DeleteModel(
            name='RatingEmployerCompany',
        ),
        migrations.DeleteModel(
            name='ReviewBranch',
        ),
    ]
