# Generated by Django 3.2 on 2024-01-02 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название филлиала')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Текстовый адрес')),
                ('link_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на адрес')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание как добраться')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.RemoveField(
            model_name='employercompany',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='accomodation_cost',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='accomodation_type',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='destination_point',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employer_dementions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_vacancy_confirmed',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='required_positions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='required_positions_reviews',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
        migrations.AddField(
            model_name='employercompany',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employercompany',
            name='iin',
            field=models.CharField(default=1, max_length=50, verbose_name='ИИН/БИН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employercompany',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество работников'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.TextField(default=1, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(default=1, max_length=50, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_increase',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default=1, max_length=5, verbose_name='Повышение зарплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_end',
            field=models.TimeField(default=timezone.datetime.now(), verbose_name='Время окончания работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_start',
            field=models.TimeField(default=timezone.datetime.now(), verbose_name='Время начала работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views_vacancy',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='ReviewBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='', verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв филиала',
                'verbose_name_plural': 'Отзывы филиалов',
            },
        ),
        migrations.CreateModel(
            name='RatingEmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг компании',
                'verbose_name_plural': 'Рейтинги компаний',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Позиция работника',
                'verbose_name_plural': 'Позиция работников',
            },
        ),
        migrations.CreateModel(
            name='DutyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название обязанности')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание обязанности')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Обязанность работника',
                'verbose_name_plural': 'Обязанности работников',
            },
        ),
        migrations.CreateModel(
            name='ClothingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название формы одежды')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Форма одежды',
                'verbose_name_plural': 'Формы одежды',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='clothingform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.clothingform', verbose_name='Форма одежды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.positionemployee', verbose_name='Позиция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dutyemployee', verbose_name='Обязанности'),
        ),
    ]
