# Generated by Django 3.2 on 2024-02-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240226_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='housing_files/', verbose_name='Файлы жилья')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.housing', verbose_name='Жилье')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.RemoveField(
            model_name='videoshousing',
            name='housing',
        ),
        migrations.DeleteModel(
            name='ImagesHousing',
        ),
        migrations.DeleteModel(
            name='VideosHousing',
        ),
    ]
