# Generated by Django 3.2 on 2024-02-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240216_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Земля', 'verbose_name_plural': 'Земли'},
        ),
        migrations.RemoveIndex(
            model_name='branch',
            name='core_branch_city_id_97ceff_idx',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='increase_choices',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='views_vacancy',
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Земля'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_person',
            field=models.CharField(default=1, max_length=255, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='email_info',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='housing_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость жилья'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страховка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type_of_housing',
            field=models.CharField(blank=True, choices=[('Provided', 'Предоставляется'), ('NotProvided', 'Не предоставляется')], max_length=50, null=True, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Текстовый адрес'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Название города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание как добраться'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='link_address',
            field=models.CharField(max_length=255, verbose_name='Ссылка на адрес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='clothingform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма одежды'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='core_branch_city_e9f930_idx'),
        ),
    ]
