# Generated by Django 3.2 on 2023-09-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_employercompany_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Избранная вакансия')),
            ],
            options={
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
