# Generated by Django 3.2 on 2024-02-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240216_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Country',
        ),
    ]
