# Generated by Django 3.2 on 2023-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favoritevacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercompany',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес Компании'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название Компании'),
        ),
    ]
