# Generated by Django 3.2 on 2024-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_housing',
            field=models.BooleanField(default=False, verbose_name='Тип жилья'),
        ),
    ]
