# Generated by Django 3.2 on 2024-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_branch_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyemployee',
            name='employer',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='clothingform',
            field=models.CharField(max_length=255, verbose_name='Форма одежды'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.DeleteModel(
            name='ClothingForm',
        ),
        migrations.DeleteModel(
            name='DutyEmployee',
        ),
    ]
