# Generated by Django 3.2 on 2024-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240110_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
    ]
