# Generated by Django 3.2 on 2023-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230905_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.CharField(blank=True, choices=[('немецкий', 'Немецкий'), ('русский', 'Русский'), ('английский', 'Английский')], default='', max_length=20, verbose_name='Язык'),
        ),
    ]
