# Generated by Django 3.2 on 2024-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vacancy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
