# Generated by Django 3.2 on 2024-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240117_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employee_count_hired',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество нанятых работников'),
        ),
    ]
