# Generated by Django 3.2 on 2023-09-12 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_user_avatar'),
        ('core', '0010_auto_20230906_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewvacancy',
            name='check_profile',
        ),
        migrations.RemoveField(
            model_name='reviewvacancy',
            name='profile_review',
        ),
        migrations.RemoveField(
            model_name='reviewvacancy',
            name='vacancy_review',
        ),
        migrations.AddField(
            model_name='reviewvacancy',
            name='applicant_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Профиль соискателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewvacancy',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Работодатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewvacancy',
            name='employer_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий работодателя'),
        ),
        migrations.AddField(
            model_name='reviewvacancy',
            name='status',
            field=models.CharField(blank=True, choices=[('Одобрено', 'Одобрено'), ('На рассмотрении', 'На рассмотрении'), ('Отказано', 'Отказано')], default='На рассмотрении', max_length=20, verbose_name='Статус отклика'),
        ),
        migrations.AddField(
            model_name='reviewvacancy',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FavoriteVacancy',
        ),
    ]
