# Generated by Django 3.2 on 2024-01-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vacancy_employee_count_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='language_english',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание английского языка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='language_german',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол'),
        ),
    ]
