# Generated by Django 3.2 on 2024-01-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принял приглашение'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отказался'),
        ),
    ]
