# Generated by Django 3.2 on 2024-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240125_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_works',
            field=models.BooleanField(default=False, verbose_name='Работает'),
        ),
    ]
