# Generated by Django 3.2 on 2024-01-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240125_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Неважно', 'Неважно')], max_length=50, verbose_name='Пол'),
        ),
    ]
