# Generated by Django 3.2 on 2024-01-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_vacancy_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='is_works',
            new_name='is_work',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positionemployee', verbose_name='Позиция'),
        ),
    ]
