# Generated by Django 3.2 on 2023-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercompany',
            name='icon',
            field=models.ImageField(blank=True, upload_to='company_icons/', verbose_name='Изображение'),
        ),
    ]
