# Generated by Django 3.2 on 2024-01-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240128_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positionemployee', verbose_name='Позиция'),
        ),
    ]
