# Generated by Django 3.2 on 2023-12-25 07:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_employercompany_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='contractadmin',
            options={'ordering': ['id'], 'verbose_name': 'Администратор для контрактов', 'verbose_name_plural': 'Администраторы для контрактов'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение на вакансию', 'verbose_name_plural': 'Приглашения на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='profilecounter',
            options={'verbose_name': 'Количество зарегистрированных пользователей', 'verbose_name_plural': 'Количество зарегистрированных пользователей'},
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='contractadmin',
            name='given_by',
            field=ckeditor.fields.RichTextField(verbose_name='Выдан (УГНС по Ленинскому району)'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='improvementidea',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст идеи'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='employer_comment',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Комментарий работодателя'),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=ckeditor.fields.RichTextField(verbose_name='Адрес на немецком'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='destination_point',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Обязанности работника'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory', verbose_name='Подкатегория'),
        ),
    ]
