# Generated by Django 3.2 on 2024-01-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240129_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='position',
        ),
    ]
