# Generated by Django 3.2 on 2023-10-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231009_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Принлашение на вакансию', 'verbose_name_plural': 'ОПриглашения на вакансии'},
        ),
    ]
