# Generated by Django 3.2 on 2024-02-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240129_0946'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='core_branch_city_id_97ceff_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company'], name='core_branch_company_9dd70f_idx'),
        ),
        migrations.AddIndex(
            model_name='employercompany',
            index=models.Index(fields=['user'], name='core_employ_user_id_bc9c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['employer'], name='core_invita_employe_6efbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['vacancy'], name='core_invita_vacancy_42e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['user'], name='core_invita_user_id_aaba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='positionemployee',
            index=models.Index(fields=['employer'], name='core_positi_employe_a49f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['branch'], name='core_review_branch__bcbb89_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['user'], name='core_review_user_id_2e241b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer_company'], name='core_vacanc_employe_84c983_idx'),
        ),
    ]
