# Generated by Django 3.2 on 2023-11-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231009_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='contractadmin',
            options={'ordering': ['id'], 'verbose_name': 'Администратор для контрактов', 'verbose_name_plural': 'Администраторы для контрактов'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение на вакансию', 'verbose_name_plural': 'Приглашения на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='profilecounter',
            options={'verbose_name': 'Количество зарегистрированных пользователей', 'verbose_name_plural': 'Количество зарегистрированных пользователей'},
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory', verbose_name='Подкатегория'),
        ),
    ]
