# Generated by Django 3.2 on 2023-11-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_invitation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractadmin',
            options={'ordering': ['id'], 'verbose_name': 'Администратор для контрактов', 'verbose_name_plural': 'Администраторы для контрактов'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение на вакансию', 'verbose_name_plural': 'Приглашения на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='profilecounter',
            options={'verbose_name': 'Количество зарегистрированных пользователей', 'verbose_name_plural': 'Количество зарегистрированных пользователей'},
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
    ]
