# Generated by Django 3.2 on 2023-11-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20231113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=128, verbose_name='Зарплата'),
        ),
    ]
