# Generated by Django 3.2 on 2023-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_serial_number', models.PositiveIntegerField(default=1)),
                ('training_serial_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Настройки CRM',
                'verbose_name_plural': 'Настройки CRM',
            },
        ),
    ]
